export const paths = {
  home: '/',
  try: '/try',
  features: '/features',
  pricing: '/pricing',
  about: '/about',
  customer: {
    login: '/customer/auth/login',
    register: '/customer/auth/register',
    forgotPassword: '/customer/auth/forgot-password',
    resetPassword: '/customer/auth/reset-password',
    verify: '/customer/auth/verify',
  },
  admin: {
    login: '/admin/auth/login',
    register: '/admin/auth/register',
    dashboard: '/admin',
    organizations: '/admin/organizations',
    organization: (id: string) => `/admin/organizations/${id}`,
    users: '/admin/users',
    system: '/admin/system',
    training: '/admin/training',
  },
  app: {
    root: '/app',
    evaluate: '/app/evaluate',
    predictions: '/app/predictions',
    prediction: (id: string) => `/app/predictions/${id}`,
    pincodes: '/app/pincodes',
    apiKeys: '/app/api-keys',
    usage: '/app/usage',
    settings: '/app/settings',
    webhooks: '/app/webhooks',
    codVerifications: '/app/cod-verifications',
    codVerification: (id: string) => `/app/cod-verifications/${id}`,
    bulkPredictions: '/app/bulk-predictions',
    developers: '/app/developers',
  },
} as const;
